### ISSUE TITLE
Transaction ID identical when sending same amount twice

### ISSUE THREAD

**Issue by Tom-MUC** [input-output-hk/shelley-testnet#14]
**Describe the bug**
When using script "faucet-send-money.sh" to send money from faucet to an address, the same amount cannot the send more than one time to the same address since jcli will generate identical transaction ID's.

**To Reproduce**
1. faucet-send-money.sh ADDRESS 1000
2. Wait until transaction is in a block
3. faucet-send-money.sh SAME_ADDRESS 1000
4. The second transaction is rejected by the node with error "Invalid UTxO: Transaction ID Already exits" (BTW, there is a typo in the error message as well)

**Expected behavior**
I expect to be able to send the same amount from address A to address B as many times as I like. Each time jcli should generate an unique transaction id.

**Additional context**
Installed release "jormungandr-v0.2.2-armv7-unknown-linux-gnueabihf.tar.gz"
Operating System: Ubuntu 16.04.5 LTS
Kernel: Linux 4.14.28-124
Architecture: armv7

**Comment by vincenthz** [comment]
Thanks @Tom-MUC for the report, looks like you found a shortcoming in the code: tracking this issue at https://github.com/input-output-hk/chain-libs/issues/25

**Comment by gmanroney** [comment]
still under investigation; see  ihttps://github.com/input-output-hk/chain-libs/issues/25  for more details as they become available

**Comment by rinor** [comment]
Can we close this one? input-output-hk/chain-libs#25 is fixed. Also tested today and all transactions went ok.
```
FAUCET_ADDR: ca1s49kpr2phpayjjzp98su2jg686t84ghekakcajdmwp4znr28ezv6wvhk264
FAUCET_PK: ed25519_pk1fdsg6sdc0fy5ssffu8z5jx37jea297dhdk8vnwmsdg5c637gnxns8f269a
FAUCET_SK: ed25519e_sk1xp02emj93tyf8lwex804w4lp7d94uhmujrl3n9kmn7mfhae6gdfyt283darfxghahp65ltvzl53tym70m2mn0r042f8ffusgdfyj9lgpsvtke
============================================================================================
  ##Create a new Account address (RECEIVER_ADDR)
RECEIVER_SK: ed25519e_sk18qx5xtq0rucrm9u0dgr8ar26knfp204pv0katxrya42268rt4pr0f063t7prfrhav4c8j996qskqagrt4j7u32gh36e63elfaf88q2sh2a7x5
RECEIVER_PK: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
RECEIVER_ADDR: ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
============================================================================================
  ##Transaction: 1: 100
## Sending 100 to ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
discrimination: testing
account: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
Success!
  ##Waiting for new block to be created (timeout = 1800 seconds)...
  ##New block was created - 483ec1510fd70e811b80a00def735de270b8faa25ee2130f771566ffe7bf100c
  ##Display the Faucet details
---
counter: 1
delegation: 6c3c6290d1066ad592996406e53d7d1e5692e4c6331ee827efda1268a71fed7d
value: 999999999890
  ##Display the RECEIVER_ADDR details
---
counter: 0
delegation: ~
value: 100
  ##Check the Receiver Account balance
  ###OK; Correct Balance; 100 = 100
  ##Check the Faucet Account balance
  ###OK; Correct Balance; 999999999890 = 999999999890
-------------------------------------------------------------------------
  ##Transaction: 2: 100
## Sending 100 to ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
discrimination: testing
account: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
Success!
  ##Waiting for new block to be created (timeout = 1800 seconds)...
  ##New block was created - 2d262bdfbdb307943764a10d3e187bd9426bcf779b1f796f545382c42797f528
  ##Display the Faucet details
---
counter: 2
delegation: 6c3c6290d1066ad592996406e53d7d1e5692e4c6331ee827efda1268a71fed7d
value: 999999999780
  ##Display the RECEIVER_ADDR details
---
counter: 0
delegation: ~
value: 200
  ##Check the Receiver Account balance
  ###OK; Correct Balance; 200 = 200
  ##Check the Faucet Account balance
  ###OK; Correct Balance; 999999999780 = 999999999780
-------------------------------------------------------------------------
  ##Transaction: 3: 100
## Sending 100 to ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
discrimination: testing
account: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
Success!
  ##Waiting for new block to be created (timeout = 1800 seconds)...
  ##New block was created - c8f440bfe8c8af6c051a6134b6c97c2cd9dabd134ef945bf1a21ddb5d357541f
  ##Display the Faucet details
---
counter: 3
delegation: 6c3c6290d1066ad592996406e53d7d1e5692e4c6331ee827efda1268a71fed7d
value: 999999999670
  ##Display the RECEIVER_ADDR details
---
counter: 0
delegation: ~
value: 300
  ##Check the Receiver Account balance
  ###OK; Correct Balance; 300 = 300
  ##Check the Faucet Account balance
  ###OK; Correct Balance; 999999999670 = 999999999670
-------------------------------------------------------------------------
  ##Transaction: 4: 100
## Sending 100 to ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
discrimination: testing
account: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
Success!
  ##Waiting for new block to be created (timeout = 1800 seconds)...
  ##New block was created - 28ccbc2b255636215a9225dd58a890eef53762056e109ed5f9ade62f8ba2df0b
  ##Display the Faucet details
---
counter: 4
delegation: 6c3c6290d1066ad592996406e53d7d1e5692e4c6331ee827efda1268a71fed7d
value: 999999999560
  ##Display the RECEIVER_ADDR details
---
counter: 0
delegation: ~
value: 400
  ##Check the Receiver Account balance
  ###OK; Correct Balance; 400 = 400
  ##Check the Faucet Account balance
  ###OK; Correct Balance; 999999999560 = 999999999560
-------------------------------------------------------------------------
  ##Transaction: 5: 100
## Sending 100 to ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
discrimination: testing
account: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
Success!
  ##Waiting for new block to be created (timeout = 1800 seconds)...
  ##New block was created - 81c7c10c257d3213ba37d469e14e5b2fca798188669cce4e7da993f9eb975e01
  ##Display the Faucet details
---
counter: 5
delegation: 6c3c6290d1066ad592996406e53d7d1e5692e4c6331ee827efda1268a71fed7d
value: 999999999450
  ##Display the RECEIVER_ADDR details
---
counter: 0
delegation: ~
value: 500
  ##Check the Receiver Account balance
  ###OK; Correct Balance; 500 = 500
  ##Check the Faucet Account balance
  ###OK; Correct Balance; 999999999450 = 999999999450
-------------------------------------------------------------------------
  ##Transaction: 6: 100
## Sending 100 to ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
discrimination: testing
account: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
Success!
  ##Waiting for new block to be created (timeout = 1800 seconds)...
  ##New block was created - a19f224525592b9b3bef6731952d033ecad24a32919513c0766af4b77a222a42
  ##Display the Faucet details
---
counter: 6
delegation: 6c3c6290d1066ad592996406e53d7d1e5692e4c6331ee827efda1268a71fed7d
value: 999999999340
  ##Display the RECEIVER_ADDR details
---
counter: 0
delegation: ~
value: 600
  ##Check the Receiver Account balance
  ###OK; Correct Balance; 600 = 600
  ##Check the Faucet Account balance
  ###OK; Correct Balance; 999999999340 = 999999999340
-------------------------------------------------------------------------
  ##Transaction: 7: 100
## Sending 100 to ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
discrimination: testing
account: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
Success!
  ##Waiting for new block to be created (timeout = 1800 seconds)...
  ##New block was created - e26a7b7d8911cd1f9f72316377d18374f21a30ee510b4495130c02accd78808b
  ##Display the Faucet details
---
counter: 7
delegation: 6c3c6290d1066ad592996406e53d7d1e5692e4c6331ee827efda1268a71fed7d
value: 999999999230
  ##Display the RECEIVER_ADDR details
---
counter: 0
delegation: ~
value: 700
  ##Check the Receiver Account balance
  ###OK; Correct Balance; 700 = 700
  ##Check the Faucet Account balance
  ###OK; Correct Balance; 999999999230 = 999999999230
-------------------------------------------------------------------------
  ##Transaction: 8: 100
## Sending 100 to ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
discrimination: testing
account: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
Success!
  ##Waiting for new block to be created (timeout = 1800 seconds)...
  ##New block was created - 48cbb07f2b54aa390d3c62da0d6b3bb1c1d07906e62cdc35dbd8201656792ec7
  ##Display the Faucet details
---
counter: 8
delegation: 6c3c6290d1066ad592996406e53d7d1e5692e4c6331ee827efda1268a71fed7d
value: 999999999120
  ##Display the RECEIVER_ADDR details
---
counter: 0
delegation: ~
value: 800
  ##Check the Receiver Account balance
  ###OK; Correct Balance; 800 = 800
  ##Check the Faucet Account balance
  ###OK; Correct Balance; 999999999120 = 999999999120
-------------------------------------------------------------------------
  ##Transaction: 9: 100
## Sending 100 to ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
discrimination: testing
account: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
Success!
  ##Waiting for new block to be created (timeout = 1800 seconds)...
  ##New block was created - 3a264cb12b108add706b0f1894ebe7b5f202dcddd8fa49c6d4dbd874e2db6e33
  ##Display the Faucet details
---
counter: 9
delegation: 6c3c6290d1066ad592996406e53d7d1e5692e4c6331ee827efda1268a71fed7d
value: 999999999010
  ##Display the RECEIVER_ADDR details
---
counter: 0
delegation: ~
value: 900
  ##Check the Receiver Account balance
  ###OK; Correct Balance; 900 = 900
  ##Check the Faucet Account balance
  ###OK; Correct Balance; 999999999010 = 999999999010
-------------------------------------------------------------------------
  ##Transaction: 10: 100
## Sending 100 to ca1s4av9wxh5dpjat5ke5xd85cpkj6a3dhtnytytj69hykslsjvfkrjq4ut6pl
discrimination: testing
account: ed25519_pk10tpt34argvh2a9kdpnfaxqd5khvtd6uezezuk3de958uynzdsusqvwv777
Success!
  ##Waiting for new block to be created (timeout = 1800 seconds)...
  ##New block was created - c568686fc3dfd427d6926c9ee643614f5e45a47ededd92a6f5f0a95761bec086
  ##Display the Faucet details
---
counter: 10
delegation: 6c3c6290d1066ad592996406e53d7d1e5692e4c6331ee827efda1268a71fed7d
value: 999999998900
  ##Display the RECEIVER_ADDR details
---
counter: 0
delegation: ~
value: 1000
  ##Check the Receiver Account balance
  ###OK; Correct Balance; 1000 = 1000
  ##Check the Faucet Account balance
  ###OK; Correct Balance; 999999998900 = 999999998900
-------------------------------------------------------------------------
```

**Comment by dorin100** [comment]
hmmm...I will give it a try tomorrow too. I tried it yesterday and it was still reproducible

**Comment by dorin100** [comment]
I confirm that this is no longer reproducible with v0.3.0.
