### ISSUE TITLE
failed to compile `jormungandr v0.3.1

### ISSUE THREAD

**Issue by lightiv** [input-output-hk/shelley-testnet#36]
**Describe the bug**
Following the guide for installing form source it fails installing jormungandr v0.3.1.  I am installing on a fresh AWS EC2 using Ubuntu Server 18.04 as recommended in the guide.

**To Reproduce**
Follow the steps in the guide to the command: cargo install --force --path jormungandr

installation runs to the error and outputs the following:

---
   Compiling actix-net v0.2.6
   Compiling jormungandr v0.3.1 (/home/ssm-user/testnet/jormungandr/jormungandr)
warning: unused import: `chain_impl_mockchain::ledger::Ledger`
  --> jormungandr/src/rest/v0/handlers.rs:13:5
   |
13 | use chain_impl_mockchain::ledger::Ledger;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: unreachable expression
  --> jormungandr/src/fragment/process.rs:93:23
   |
93 |                     B(future::ok(unimplemented!()))
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unreachable_code)] on by default

error[E0277]: the size for values of type `(dyn std::error::Error + 'static)` cannot be known at compilation time
   --> jormungandr/src/network/mod.rs:400:1
    |
400 | / custom_error! {
401 | |     pub FetchBlockError
402 | |         NoTrustedPeers = "no trusted peers specified",
403 | |         Connect { source: Box<Error> } = "connection to peer failed",
404 | |         GetBlocks { source: core_error::Error } = "block request failed",
405 | |         NoBlocks = "no blocks in the stream",
406 | | }
    | |_^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `(dyn std::error::Error + 'static)`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: required because of the requirements on the impl of `std::error::Error` for `std::boxed::Box<(dyn std::error::Error + 'static)>`
    = note: required for the cast to the object type `dyn std::error::Error`
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: failed to compile `jormungandr v0.3.1 (/home/ssm-user/testnet/jormungandr/jormungandr)`, intermediate artifacts can be found at `/home/ssm-user/testnet/jormungandr/target`

Caused by:
  Could not compile `jormungandr`.
---

**Expected behavior**
Expected for it to successfully install

**Additional context**
I have deleted the host and recreated it but it still fails at this point.
[jormungandr_err.txt](https://github.com/input-output-hk/shelley-testnet/files/3444534/jormungandr_err.txt)

**Comment by rinor** [comment]
Will be fixed once [this](https://github.com/input-output-hk/jormungandr/pull/662) pull request is merged into [jormungandr](https://github.com/input-output-hk/jormungandr) main branch.

Just FYI is not related to jormungandr itself, but to an external library that was updated _21 hours ago_

**Comment by rinor** [comment]
Fixed. Please try and report back.

**Comment by hodlonaut** [comment]
Seems to be compiling okay for me at the moment

**Comment by lightiv** [comment]
Ok, @rinor looks like you are already aware for he problem below: "Edit: Still broken, different error, but same cause. Tracked at input-output-hk/jormungandr#663"

It appears that I got the same error  This is on a freshly created AWS virtual machine and following the guide from the beginning.

--
   Compiling jormungandr v0.3.1 (/home/ssm-user/testnet/jormungandr/jormungandr)
warning: unused import: `chain_impl_mockchain::ledger::Ledger`
  --> jormungandr/src/rest/v0/handlers.rs:13:5
   |
13 | use chain_impl_mockchain::ledger::Ledger;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: unreachable expression
  --> jormungandr/src/fragment/process.rs:93:23
   |
93 |                     B(future::ok(unimplemented!()))
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unreachable_code)] on by default

error[E0277]: the trait bound `std::boxed::Box<bincode::ErrorKind>: std::borrow::Borrow<dyn std::error::Error>` is not satisfied
  --> jormungandr/src/network/p2p/topology.rs:17:1
   |
17 | / custom_error! {pub Error
18 | |     Encoding { source: bincode::Error } = "Serialization error",
19 | |     Io { source: io::Error } = "I/O Error",
20 | | }
   | |_^ the trait `std::borrow::Borrow<dyn std::error::Error>` is not implemented for `std::boxed::Box<bincode::ErrorKind>`
   |
   = help: the following implementations were found:
             <std::boxed::Box<T> as std::borrow::Borrow<T>>
   = note: required by `std::borrow::Borrow::borrow`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: failed to compile `jormungandr v0.3.1 (/home/ssm-user/testnet/jormungandr/jormungandr)`, intermediate artifacts can be found at `/home/ssm-user/testnet/jormungandr/target`

Caused by:
  Could not compile `jormungandr`.
---

**Comment by disassembler** [comment]
One suggestion. If you only want to run jormungandr and not develop it, you don't need to build it yourself. You could use a precompiled binary using snappy package using `snap install jormungandr` or follow the instructions in `jormungandr-nix` to use it via a `nix-shell`. If you want use this as a development environment, this is fixed on master and the upcoming release will resolve it.

**Comment by lightiv** [comment]
Yes, thanks.  I switch to a precompiled Win64 binary and installed fine.  I followed one of the videos for this.  Now to really figure out what is happening.  :)
