### ISSUE TITLE
All trusted-peers are down/not responding when starting the local node

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/shelley-testnet#65]
**Describe the bug**
All trusted-peers are down/not responding when starting the local node.

**To Reproduce**
1. Start the local node using the provided trusted-peers --> sometimes the node will not start because the block0 cannot be downloaded from any of the trusted peers.

**Expected behavior**
Trusted peers (or at least one of them) should always provided the block0 to any node requesting it.

**Additional context**
![image](https://user-images.githubusercontent.com/29144964/65870671-6bc8fb80-e385-11e9-86f6-04e22ae702e0.png)

**Comment by dkijania** [comment]
can we close this one ? looks like it describing temporary situation it is resolved by now (?) connected more with test net rather than software

**Comment by dorin100** [comment]
Nope. We have this open here in order to track it with @iohk-devops . As I know this is still not fixed and we see it intermittently.

**Comment by dorin100** [comment]
closing this issue as the trusted peers stability and availability was improved.
